# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIShiftScheduler_KE3',
                'doc_host': 'https://kobus78.github.io',
                'git_url': 'https://github.com/kobus78/AIShiftScheduler_KE3',
                'lib_path': 'AIShiftScheduler_KE3'},
  'syms': {'AIShiftScheduler_KE3.core': {'AIShiftScheduler_KE3.core.foo': ('core.html#foo', 'AIShiftScheduler_KE3/core.py')}}}
